### PR TITLE
Use usernames as project name defaults for tests.

### PR DESCRIPTION
**Pull request by ryan-roemer**

### CODE REVIEW

**Comment by kriuz** [comment]
Is there a way right now, when used with Magellan, to have SAUCE_NAME, be the name of the test itself?.

**Comment by ryan-roemer** [comment]
This was released in `v0.3.4`. ( https://github.com/FormidableLabs/rowdy/compare/v0.3.3...v0.3.4 )

Can you upgrade to that and see if `SAUCE_NAME` is picked up?

**Comment by ryan-roemer** [comment]
I think you can maybe just do a version bump here? https://github.com/TestArmada/boilerplate-mocha-webdriverio/blob/master/package.json#L14

/cc @Maciek416

**Comment by kriuz** [comment]
This is not quite what I was looking for. Magellan starts a new instance of the browser for every test. I'm looking for a way to have that test's name, e.g ("should show ...") be the that appears in SauceLabs as the name of that run. The update on v0.3.4 set this value to the SauceLabs username. I was looking at the code for both magellan and rowdy and didn't really see a way of doing that. Thanks for the help.

**Comment by ryan-roemer** [comment]
@kriuz -- So you'd like (as a strawman):

```
    sauceLabs: {
      default: {
        desiredCapabilities: {
          name: function () {
            return mocha.CURRENT_TEST_NAME;
          },
          tags: [SAUCE_TAG],
          public: "public",
          build: BUILD
        },
```

?

**Comment by kriuz** [comment]
Exactly.

**Comment by geekdave** [comment]
@kriuz Could you please file an issue for this in the Magellan repo?  This is something I think we need to implement in Magellan's mocha interop layer.

**Comment by kriuz** [comment]
@geekdave Will do, thanks for the help.

**Pull request merged**
